### ISSUE TITLE
The task can't continue when one of the subtask crash

### ISSUE THREAD

**Issue by Linjovi** [brizer/multi-repo-git#2]
For example, I have three repos in project list, but the second one is not exist. Then the process will crash when go to the second one, and the third one will not be executed.

**Comment by brizer** [comment]
I will provide a quiet mode.

**Comment by brizer** [comment]
You can upgrade your `mrgx` to 1.6.0, and use `mrgx -q ***` to solve this problem.
Read from [here](https://github.com/brizer/multi-repo-git/blob/master/readme.md#-q---quiet) for more details.
