### ISSUE TITLE
not support git commit -m"**"

### ISSUE THREAD

**Issue by WebRookieSyb** [brizer/multi-repo-git#8]
if use `mrgx git commit -m"**"`, it is not support. we must use`mrgx git commit -m "**"`

**Comment by brizer** [comment]
I did not reproduce this problem：

<img src="https://raw.githubusercontent.com/brizer/graph-bed/master/img/20191113204040.png"/>

Please determine if the problem exists and provide your error message, preferably a screenshot. There is also the version of your `mrgx` and `nodejs`.

**Comment by WebRookieSyb** [comment]
sorry,it was my mistake
